let data= [
    {
        id: 12345,
        email: "stephanie@student.ehb.be",
        role: "student",
        items: 2,
    },
    {
        id: 12364,
        email: "selma@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 78851,
        email: "raphaël@student.ehb.be",
        role: "student",
        items: 4,
    },
    {
        id: 36511,
        email: "ruben.dejonkheere@docent.ehb.be",
        role: "docent",
        items: 7,
    },
    {
        id: 78945,
        email: "mohamed@student.ehb.be",
        role: "student",
        items: 2,
    },
    {
        id: 15423,
        email: "zakaria@student.ehb.be",
        role: "student",
        items: 5,
    },
    {
        id: 14697,
        email: "kevin.felix@docent.ehb.be",
        role: "docent",
        items: 3,
    },
    {
        id: 14235,
        email: "thomas@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 47625,
        email: "david.vansteertegem@docent.ehb.be",
        role: "docent",
        items: 1,
    },
    {
        id: 45217,
        email: "talula@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 46212,
        email: "wim.hambrouck@docent.ehb.be",
        role: "docent",
        items: 10,
    },
    {
        id: 78226,
        email: "alex@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 59812,
        email: "sarah@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 45786,
        email: "gwen@student.ehb.be",
        role: "student",
        items: 3,
    },
    {
        id: 12345,
        email: "stephanie@student.ehb.be",
        role: "student",
        items: 2,
    },
    {
        id: 12364,
        email: "selma@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 78851,
        email: "raphaël@student.ehb.be",
        role: "student",
        items: 4,
    },
    {
        id: 36511,
        email: "ruben.dejonkheere@docent.ehb.be",
        role: "docent",
        items: 7,
    },
    {
        id: 78945,
        email: "mohamed@student.ehb.be",
        role: "student",
        items: 2,
    },
    {
        id: 15423,
        email: "zakaria@student.ehb.be",
        role: "student",
        items: 2,
    },
    {
        id: 14697,
        email: "kevin.felix@docent.ehb.be",
        role: "docent",
        items: 3,
    },
    {
        id: 14235,
        email: "thomas@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 47625,
        email: "david.vansteertegem@docent.ehb.be",
        role: "docent",
        items: 1,
    },
    {
        id: 45217,
        email: "talula@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 46212,
        email: "wim.hambrouck@docent.ehb.be",
        role: "docent",
        items: 10,
    },
    {
        id: 78226,
        email: "alex@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 59812,
        email: "sarah@student.ehb.be",
        role: "student",
        items: 1,
    },
    {
        id: 45786,
        email: "gwen@student.ehb.be",
        role: "student",
        items: 3,
    },
//kunnen nog meer toevoegen indien nodig
]; 
export default data;